In [1]:
import numpy as np
from sklearn import preprocessing
import pandas as pd

In [2]:
A = np.array([
    [1, 3, -2, 1, 5, 13, 1],
    [3, 4, 5, -2, 4, 11, 3],
    [4, 5, 2, 2, 6, 8, -1],
]).T
print(A)

[[ 1  3  4]
 [ 3  4  5]
 [-2  5  2]
 [ 1 -2  2]
 [ 5  4  6]
 [13 11  8]
 [ 1  3 -1]]


In [3]:
poly=preprocessing.PolynomialFeatures(degree=2,include_bias=True)
poly.fit(A)
a_poly=poly.transform(A)
pd.DataFrame(a_poly)

0     1     2    3      4      5      6      7     8     9
0  1.0   1.0   3.0  4.0    1.0    3.0    4.0    9.0  12.0  16.0
1  1.0   3.0   4.0  5.0    9.0   12.0   15.0   16.0  20.0  25.0
2  1.0  -2.0   5.0  2.0    4.0  -10.0   -4.0   25.0  10.0   4.0
3  1.0   1.0  -2.0  2.0    1.0   -2.0    2.0    4.0  -4.0   4.0
4  1.0   5.0   4.0  6.0   25.0   20.0   30.0   16.0  24.0  36.0
5  1.0  13.0  11.0  8.0  169.0  143.0  104.0  121.0  88.0  64.0
6  1.0   1.0   3.0 -1.0    1.0    3.0   -1.0    9.0  -3.0   1.0

In [4]:
def polynomial_regression(X, y, k):
    poly = preprocessing.PolynomialFeatures(degree=k, include_bias=True)
    X_poly = poly.fit_transform(X)
    w_hat = np.linalg.inv(X_poly.T@X_poly)@X_poly.T@y
    y_pred = X_poly @ w_hat
    return X_poly, y_pred, w_hat

In [5]:
A = boston_data[['LSTAT', 'PTRATIO', 'RM', 'CRIM']]
y = boston_data[['PRICE']]
 
A_poly, y_pred, w_hat = polynomial_regression(A, y, 1)
A_poly2, y_pred2, w_hat2 = polynomial_regression(A, y, 2)
A_poly3, y_pred3, w_hat3 = polynomial_regression(A, y, 3)
A_poly4, y_pred4, w_hat4 = polynomial_regression(A, y, 4)
A_poly5, y_pred5, w_hat5 = polynomial_regression(A, y, 5)

NameError: name 'boston_data' is not defined

In [ ]:
x1=1
x2=4
model=10.4 + 8*x1+0.5*x2 + 3*(x1*x1) + 0.4*(x2*x2) + 0 *x1*x2
model

29.799999999999997

In [ ]:
array=np.array([[1,1,1,1],[1,3,-2,9],[1,9,4,81]]).T
array

array([[ 1,  1,  1],
       [ 1,  3,  9],
       [ 1, -2,  4],
       [ 1,  9, 81]])

In [ ]:
array_y=np.array([3,7,-5,21]).T

In [ ]:
y_1=np.linalg.inv(array.T@array)@array.T@array_y

In [ ]:
y_1

array([ 0.11446013,  2.46095638, -0.01608801])

In [ ]:
A=np.array([[1,1,1,1,1],[5,9,4,3,5],[15,18,18,19,19],[7,6,7,7,7]]).T
y=np.array([24,22,35,33,36])


a=1
E=np.eye(4)
alpha = 1

In [ ]:

# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
w_hat_ridge = np.linalg.inv(A.T@A+alpha*E)@A.T@y
print(w_hat_ridge.round(2)) 

[-0.09 -1.71  1.91  0.73]


In [ ]:
coef=np.linalg.inv(A.T@A +a* E) @ A.T @ y
coef.round(2)

array([-0.09, -1.71,  1.91,  0.73])

In [ ]:
from sklearn.linear_model import Ridge

model=Ridge(solver='svd')

model.fit(A,y)


model.coef_.round(2)
model.intercept_

np.float64(24.451977401129945)

In [ ]:
import numpy as np

In [ ]:
array=np.array([[3,1],[2,2]]).T
array

array([[3, 2],
       [1, 2]])

In [ ]:
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(array)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [4. 1.]
Собственные векторы: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
A=np.array([[1,4,13],[3,-4,7],[5,9,12]]).T
A

values,arrays=np.linalg.eig(A)
print(np.round(values))
print(arrays)


[20. -4. -7.]
[[-0.29813912 -0.73141292  0.25078429]
 [-0.38491044  0.59044076 -0.95097448]
 [-0.87347411  0.34119621  0.18098281]]


In [ ]:
A_1=np.array([[1,9,4],[9,4,7],[4,7,12]]).T

matrix_Gram=A_1.T@A_1

own_values,own_arrays=np.linalg.eig(matrix_Gram)

np.round(own_values)

array([391.,  46.,  16.])

In [8]:
x1=np.array([1,2,1,1])
x2=np.array([70,130,65,60])

In [15]:
A=np.array([x1,x2]).T
A=np.matrix([x1,x2]).T
A

matrix([[  1,  70],
        [  2, 130],
        [  1,  65],
        [  1,  60]])

In [20]:
import pandas as pd
matrixx=pd.DataFrame(A).corr()

In [21]:
values,arrays=np.linalg.eig(matrixx)

In [30]:
arrays

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [33]:
s=np.std(arrays[0][0]*x1+arrays[0][1]*x2)

In [36]:
np.linalg.norm(x1)

np.float64(2.6457513110645907)

In [35]:
a=arrays[0][0]*x1+arrays[0][1]*x2

((a-np.mean(a))/s).round(2)

array([ 0.39, -1.72,  0.57,  0.75])

In [29]:
arrays[0][1]*x2

array([-49.49747468, -91.92388155, -45.96194078, -42.42640687])

In [37]:
C = np.array([[1, 0.8], [0.8, 1]])

eig_values, eig_vectors = np.linalg.eig(C)

In [38]:
eig_values

array([1.8, 0.2])

In [39]:
eig_vectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])