In [1]:
import numpy as np

In [2]:
S=np.array([1,2,3,4])
print(S[2])
print(len(S))

3
4


In [3]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [4]:
t[6]==t.max()

np.True_

In [5]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

0.2*b

array([1. , 1.2, 1.4, 1.6])

In [6]:
w=np.array([-6118,220.8,0,332.2,563,0])
x=np.array([1,45,1,25.175,2,1])
np.dot(w,x)

np.float64(13307.135)

In [7]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [8]:
Hut_Paradise_DF.values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [ ]:
Array_not_live = Hut_Paradise_DF.values[:,1] - Hut_Paradise_DF.values[:,5]
Array_not_live

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

In [ ]:
X=np.array([10,20,30,15,5,40,20,8,20])

skalyar=np.dot(X,Hut_Paradise_DF.values[:,4])
skalyar

np.int64(1348)

In [11]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [12]:
s=2*v +(-3)*w
s

array([-3, 14,  3,  4,  2])

In [ ]:
0==np.dot(u,s)

np.True_

In [ ]:
a=np.matrix([3,4])
a.shape

(1, 2)

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [15]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [ ]:
Inc=np.matrix([Husband_Income,Wife_Income,Mother_In_Law_Income]).T

print(f'{Inc[0,0]},{Inc[1,1]},{Inc[2,2]}')


100,200,100


Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [ ]:
Cons=np.matrix([Husband_Consumption,Wife_Consumption,Mother_In_Law_Consumption]).T
print(f'{Cons[0,0]},{Cons[1,1]},{Cons[2,2]}')

50,80,140


Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу Inc, где доходы расположены по столбцам.

Выберите список элементов из первой строки этой матрицы (строки нумеруются с 1):

In [ ]:
A=(Inc-(Inc*0.13))
A[0]

matrix([[ 87. , 130.5,  78.3]])

Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

Выберите список элементов из третьей строки этой матрицы:

In [19]:
P=A-Cons
P[2]

matrix([[ 61.8, -26.9, -53. ]])

In [20]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [ ]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [ ]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [23]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])


In [ ]:
np.dot(A, x.T)

array([26, 30])

In [25]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [26]:
B

array([[ 1, -1,  0,  1,  1],
       [-2,  0,  2, -1,  1]])

In [27]:
np.dot(A.T,B)

ValueError: shapes (4,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

In [67]:
np.dot(A.T,B)[1,4]

matrix([[ 6],
        [11],
        [ 1],
        [ 5]])

In [79]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A=np.array([x,y,z])
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [84]:
G=np.dot(A.T,A)
G

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [86]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [98]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [99]:
Count_DF 

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [119]:
((Price_DF * Count_DF)*com).T.sum()

Аня      11.30
Борис    15.22
Вика     11.90
Галя     20.60
Дима     41.90
Егор     21.20
Женя     11.49
Юра      38.25
dtype: float64

In [110]:
(Price_DF * Count_DF).T

Аня  Борис  Вика  Галя  Дима  Егор  Женя   Юра
Женские стрижки  20.0    3.6  24.0   7.2  15.0  50.0  24.2  31.5
Мужские стрижки   7.5   52.5  24.0   9.6  87.5  15.0   1.0   0.0
Окрашивания      12.0    3.0   0.0  50.4  54.0   6.0   6.0  77.5
Укладка          12.0   25.0  15.0  11.2  25.0  34.0  12.5  31.0
Уход             10.0    6.0   8.0  10.0  27.0  30.0  34.0  56.0

In [111]:
np.dot(com,(Price_DF * Count_DF).T)

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [123]:
((Price_DF * Count_DF) *(1-com)).T.sum()

Аня       50.20
Борис     74.88
Вика      59.10
Галя      67.80
Дима     166.60
Егор     113.80
Женя      66.21
Юра      157.75
dtype: float64

In [130]:
np.dot(1-com,(Price_DF * Count_DF).T)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [131]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [132]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [136]:
import numpy as np
A = np.matrix ("1, 2; 3, 4")
print(np.linalg.det(A))

-2.0000000000000004


In [30]:
a=np.array([4,1,0])
b=np.array([-1,4,0])
c=np.array([0,0,1])
A = np.array([a, b, c]).T
print(np.linalg.matrix_rank(A)) 


3


In [34]:
A= np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
A

array([[ 8,  6, 11],
       [ 7,  5,  9],
       [ 6, 10,  6]])

In [39]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [41]:
np.linalg.inv(A)[1,0]

np.float64(0.375)

In [42]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [44]:
A=np.matrix([v1,v2,v3,v4]).T
A

matrix([[ 9,  2,  4,  3],
        [10,  0,  0, -4],
        [ 7,  5,  0,  3],
        [ 7,  1,  4, -1],
        [ 9,  4,  1, -4]])

In [45]:
rank=np.linalg.matrix_rank(A)
rank

np.int64(4)

In [48]:
Grama=np.dot(A.T,A)
Grama[0,3]

np.int64(-35)

In [51]:
Grama

matrix([[360,  96,  73, -35],
        [ 96,  46,  16,   4],
        [ 73,  16,  33,   4],
        [-35,   4,   4,  51]])

In [50]:
np.linalg.det(Grama).round()

np.float64(3716648.0)

In [53]:
np.linalg.inv(Grama)[2,0].round(3)

np.float64(-0.026)

In [55]:
a=np.array([2,10,-2]).T
b=np.array([3,2,-2]).T
c=np.array([8,14,-6]).T

A=np.matrix([a,b,c])
print(np.linalg.matrix_rank(A))

2


In [35]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
from sklearn import datasets # для импорта данных
import seaborn as sns # для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

# загружаем датасет
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']
boston_data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)
boston_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [36]:
boston_data.shape

(506, 14)

In [41]:
np.ones(506)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [42]:
CRIM=boston_data['CRIM']
RM=boston_data['RM']
A=np.column_stack((np.ones(506),CRIM,RM))
y = boston_data[['PRICE']]
print(A)

[[1.0000e+00 6.3200e-03 6.5750e+00]
 [1.0000e+00 2.7310e-02 6.4210e+00]
 [1.0000e+00 2.7290e-02 7.1850e+00]
 ...
 [1.0000e+00 6.0760e-02 6.9760e+00]
 [1.0000e+00 1.0959e-01 6.7940e+00]
 [1.0000e+00 4.7410e-02 6.0300e+00]]


In [43]:
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat.values)

[[-29.24471945]
 [ -0.26491325]
 [  8.39106825]]


In [52]:
CRIM_NEW=0.1
RM_NEW= 8 
price_NEW=(w_hat.values[0] +w_hat.values[1]*CRIM_NEW + w_hat.values[2]*RM_NEW).round()
price_NEW

array([38.])

In [65]:
np.array((1,CRIM_NEW,RM_NEW))

array([1. , 0.1, 8. ])

In [75]:
w_hat

PRICE
0 -29.244719
1  -0.264913
2   8.391068

In [74]:
np.array([1,CRIM_NEW,RM_NEW]) @ w_hat

PRICE    37.857335
dtype: float64

In [69]:
# короткий способ сделать прогноз
new=np.array([[1,CRIM_NEW,RM_NEW]])
print('prediction:', (new@w_hat).values)

prediction: [[37.85733519]]


In [78]:
CRIM_1=0.2
RM_1=6

In [82]:
w_hat

PRICE
0 -29.244719
1  -0.264913
2   8.391068

In [83]:
np.array([CRIM_1,RM_1])

array([0.2, 6. ])

In [89]:
np.array([1,CRIM_1,RM_1])@w_hat

PRICE    21.048707
dtype: float64

In [90]:
x0=np.array([1,1,1,1])
x1=np.array([1,1,0,2])
x2=np.array([-1,1,0,0])
x3=np.array([0,2,0,2])

In [95]:
A=np.array([x0,x1,x2,x3]).T
y=np.array([1,2,1,2])

array([[ 1,  1, -1,  0],
       [ 1,  1,  1,  2],
       [ 1,  0,  0,  0],
       [ 1,  2,  0,  2]])

In [96]:
w_hat=np.linalg.inv(A.T@A)@A.T@y

LinAlgError: Singular matrix

In [97]:
boston_data[['CHAS', 'LSTAT', 'CRIM','RM']].describe()

CHAS       LSTAT        CRIM          RM
count  506.000000  506.000000  506.000000  506.000000
mean     0.069170   12.653063    3.613524    6.284634
std      0.253994    7.141062    8.601545    0.702617
min      0.000000    1.730000    0.006320    3.561000
25%      0.000000    6.950000    0.082045    5.885500
50%      0.000000   11.360000    0.256510    6.208500
75%      0.000000   16.955000    3.677083    6.623500
max      1.000000   37.970000   88.976200    8.780000

In [100]:
# составляем матрицу наблюдений и вектор целевой переменной
A = np.column_stack((np.ones(506), boston_data[['CHAS', 'LSTAT', 'CRIM','RM']]))
y = boston_data[['PRICE']]
# вычисляем OLS-оценку для коэффициентов без стандартизации
w_hat=np.linalg.inv(A.T@A)@A.T@y
print(w_hat.values.round(2))

[[-1.92]
 [ 4.  ]
 [-0.58]
 [-0.1 ]
 [ 5.08]]


In [112]:
A=boston_data[['CHAS', 'LSTAT', 'CRIM','RM']]
y=boston_data['PRICE']

A_cent=A-A.mean(axis=0)
A_st = A_cent/np.linalg.norm(A_cent, axis=0)

In [113]:
A_st.describe().round(2)

CHAS   LSTAT    CRIM      RM
count  506.00  506.00  506.00  506.00
mean    -0.00   -0.00   -0.00   -0.00
std      0.04    0.04    0.04    0.04
min     -0.01   -0.07   -0.02   -0.17
25%     -0.01   -0.04   -0.02   -0.03
50%     -0.01   -0.01   -0.02   -0.00
75%     -0.01    0.03    0.00    0.02
max      0.16    0.16    0.44    0.16

In [114]:
print(np.linalg.norm(A_st, axis=0))

[1. 1. 1. 1.]


In [115]:
# стандартизируем вектор целевой переменной
y_cent = y - y.mean()
y_st = y_cent/np.linalg.norm(y_cent)

In [116]:
# вычислим OLS-оценку для стандартизированных коэффициентов
w_hat_st=np.linalg.inv(A_st.T@A_st)@A_st.T@y_st
print(w_hat_st.values)

[ 0.11039956 -0.45220423 -0.09108766  0.38774848]


In [117]:
A_st.T @ A_st

CHAS     LSTAT      CRIM        RM
CHAS   1.000000 -0.053929 -0.055892  0.091251
LSTAT -0.053929  1.000000  0.455621 -0.613808
CRIM  -0.055892  0.455621  1.000000 -0.219247
RM     0.091251 -0.613808 -0.219247  1.000000

In [122]:
x=np.array([12,8]).T
x

array([12,  8])

In [123]:
mean_x=x-x.mean(axis=0)
mean_x

array([ 2., -2.])

In [125]:
np.linalg.norm(mean_x)

np.float64(2.8284271247461903)

In [127]:
x_cent=mean_x/np.linalg.norm(mean_x,axis=0)

x_cent.round(3)

array([ 0.707, -0.707])

In [34]:
v=np.array([5,1,2])
u=np.array([4,2,8])

np.corrcoef(v,u)

array([[1.        , 0.05241424],
       [0.05241424, 1.        ]])

In [37]:
v_mean=v-v.mean()
u_mean=u-u.mean()

In [40]:
v_mean

array([ 2.33333333, -1.66666667, -0.66666667])

In [39]:
array_mean=v_mean @ u_mean
array_mean

np.float64(0.666666666666667)

In [44]:
array_mean/np.sqrt((v_mean@ v_mean) * (u_mean@u_mean))

np.float64(0.05241424183609594)

In [67]:
x1=np.array([5.1,1.8,2.1,10.3,12.1,12.6])
x2=np.array([10.2,3.7,4.1,20.5,24.2,24.1])
x3=np.array([2.5,0.9,1.1,5.1,6.1,6.3])

matrix=np.matrix([x1,x2,x3])

crl=np.corrcoef(matrix)


In [75]:
pd.DataFrame(crl)

0         1         2
0  1.000000  0.999255  0.999837
1  0.999255  1.000000  0.999066
2  0.999837  0.999066  1.000000

In [71]:
np.linalg.matrix_rank(pd.DataFrame(crl))

np.int64(3)

In [73]:
np.linalg.det(pd.DataFrame(crl)).round(7)

np.float64(5e-07)